// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}
