// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFiles(arg1:Array<string>):Promise<void>;

export function GetOS():Promise<string>;

export function ListDir(arg1:string):Promise<Array<string>>;

export function PickFolder():Promise<string>;
